using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace AptekaAPI.Models
{
    public class Country
    {
        [Key, JsonIgnore]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required, MinLength(3), MaxLength(32)]
        public string Name { get; set; }
    }
    public class CountryView
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
    public class CountyList
    {
        public
            List<string> x = new(200)
            {
                "Afgʻoniston",
                "Albaniya",
                "Amerika Qoʻshma Shtatlari",
                "Andorra",
                "Angola",
                "Antigua va Barbuda",
                "Argentina",
                "Armaniston",
                "Avstraliya",
                "Avstriya",
                "Bagamalar",
                "Bahrayn",
                "Bangladesh",
                "Barbados",
                "Belarus",
                "Belgiya",
                "Beliz",
                "Benin",
                "Birlashgan Arab Amirliklari",
                "Birma",
                "Bolgariya",
                "Boliviya",
                "Bosniya va Gersegovina",
                "Botsvana",
                "Braziliya",
                "Bruney",
                "Buyuk Britaniya",
                "Burkina Faso",
                "Burundi",
                "Butan",
                "Daniya",
                "Dominika",
                "Dominika Respublikasi",
                "Efiopiya",
                "Ekvador",
                "Ekvatorial Gvineya",
                "Eritreya",
                "Eron",
                "Estoniya",
                "Eswatini",
                "Fiji",
                "Filippin",
                "Finlyandiya",
                "Fransiya",
                "Gabon",
                "Gaiti",
                "Gambiya",
                "Gana",
                "Germaniya",
                "Gonduras",
                "Grenada",
                "Gretsiya",
                "Gruziya",
                "Guyana",
                "Gvatemala",
                "Gvineya",
                "Gvineya-Bisau",
                "Hindiston",
                "Indoneziya",
                "Iordaniya",
                "Irlandiya",
                "Iroq",
                "Islandiya",
                "Ispaniya",
                "Isroil",
                "Italiya",
                "Janubiy Afrika",
                "Janubiy Koreya",
                "Janubiy Sudan",
                "Jazoir",
                "Jibuti",
                "Kabo-Verde",
                "Kambodja",
                "Kamerun",
                "Kanada",
                "Keniya",
                "Kipr",
                "Kiribati",
                "Kolumbiya",
                "Komoros",
                "Kongo Demokratik Respublikasi",
                "Kongo Respublikasi",
                "Kosta Rika",
                "Kot-d'Ivuar",
                "Kuba",
                "Laos",
                "Latviya",
                "Lesoto",
                "Liberiya",
                "Litva",
                "Livan",
                "Liviya",
                "Lixtenshteyn",
                "Luksemburg",
                "Madagaskar",
                "Makedoniya",
                "Malavi",
                "Malayziya",
                "Maldiv Respublikasi",
                "Mali",
                "Malta",
                "Markaziy Afrika Respublikasi",
                "Marokash",
                "Marshall Orollari",
                "Mavrikiy",
                "Mavritaniya",
                "Meksika",
                "Mikroneziya",
                "Misr",
                "Moldova",
                "Monako",
                "Mongoliya",
                "Montenegro",
                "Mozambik",
                "Namibiya",
                "Nauru",
                "Nepal",
                "Niger",
                "Nigeriya",
                "Niderlandiya",
                "Nikaragua",
                "Norvegiya",
                "Oman",
                "Ozarbayjon",
                "Palau",
                "Panama",
                "Papua-Yangi Gvineya",
                "Paragvay",
                "Peru",
                "Pokiston",
                "Polsha",
                "Portugaliya",
                "Qatar",
                "Qirgʻiziston",
                "Qozogʻiston",
                "Quvayt",
                "Rossiya",
                "Ruanda",
                "Ruminiya",
                "Salvador",
                "Samoa",
                "San Marino",
                "San-Tome va Prinsipi",
                "Saudiya Arabistoni",
                "Senegal",
                "Sent-Kits va Nevis",
                "Sent Lusiya",
                "Sent Vinsent va Grenadinlar",
                "Serbiya",
                "Seyshell orollari",
                "Shimoliy Koreya",
                "Singapur",
                "Slovakiya",
                "Sloveniya",
                "Solomon Orollari",
                "Somali",
                "Sudan",
                "Surinam",
                "Suriya",
                "Syerra-Leone",
                "Tailand",
                "Tanzaniya",
                "Togo",
                "Tojikiston",
                "Tonga",
                "Trinidad va Tobago",
                "Tunis",
                "Turkiya",
                "Turkmaniston",
                "Tuvalu",
                "Uganda",
                "Ukraina",
                "Urugvay",
                "Vanuatu",
                "Vatikan",
                "Venesuela",
                "Vengriya",
                "Vyetnam",
                "Xitoy",
                "Xorvatiya",
                "Yaman",
                "Yamayka",
                "Yangi Zelandiya",
                "Yaponiya",
                "Zambiya",
                "Zimbabve",
                "Oʻzbekiston",
                "Sharqiy Timor",
                "Shri Lanka",
                "Shvetsiya",
                "Shveytsariya",
                "Chad",
                "Chexiya",
                "Chili"
            };
    }
}
